### ISSUE TITLE
nowplaying returns error

### ISSUE THREAD

**Issue by PABHudds** [antxxxx/sonos-swagger-api#1]
When I use nowplaing for any room I get teh following error. Could this be to do with the fact that teh radio station playing was launched by Alexa?

Request: http://localhost:10010/players/kitchen/nowplaying

Result: {
  "message": "Cannot add property uriMetadata, object is not extensible",
  "stack": "TypeError: Cannot add property uriMetadata, object is not extensible\n    at Promise.resolve.then (D:\\Project\\sonos-swagger-api\\api\\helpers\\nowPlaying.js:12:38)\n    at bound (domain.js:301:14)\n    at runBound (domain.js:314:12)\n    at tryCatcher (D:\\Project\\sonos-swagger-api\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (D:\\Project\\sonos-swagger-api\\node_modules\\bluebird\\js\\release\\promise.js:512:31)\n    at Promise._settlePromise (D:\\Project\\sonos-swagger-api\\node_modules\\bluebird\\js\\release\\promise.js:569:18)\n    at Promise._settlePromiseCtx (D:\\Project\\sonos-swagger-api\\node_modules\\bluebird\\js\\release\\promise.js:606:10)\n    at Async._drainQueue (D:\\Project\\sonos-swagger-api\\node_modules\\bluebird\\js\\release\\async.js:138:12)\n    at Async._drainQueues (D:\\Project\\sonos-swagger-api\\node_modules\\bluebird\\js\\release\\async.js:143:10)\n    at Immediate.Async.drainQueues (D:\\Project\\sonos-swagger-api\\node_modules\\bluebird\\js\\release\\async.js:17:14)\n    at runCallback (timers.js:800:20)\n    at tryOnImmediate (timers.js:762:5)\n    at processImmediate [as _immediateCallback] (timers.js:733:5)",
  "code": "error"
}

**Comment by antxxxx** [comment]
Yes its possible that it has to do with it being launched by Alexa. I wrote this before Alexa and I know that some of the way data is returned when it is started by Alexa is different.   
I will take a look

**Comment by antxxxx** [comment]
Looks like I actually fixed this a while ago, but had forgot to merge it into master.   
I have merged the code in now and it seems to work for me. Can you test the latest code please
